# chart-repo: stable/nginx-ingress
# chart-version: 1.4.0

nameOverride: nginx-ingress

controller:
  replicaCount: 1
  service:
    targetPorts:
      http: http
      https: http
  config:
    use-forwarded-headers: "true"
